// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  try {
    // Use import.meta.env for client-side (Vite build-time replacement)
    // Fall back to process.env for SSR (server-side rendering)
    const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    });

    console.log('[Supabase] Client initialized successfully');
    return client;
  } catch (error) {
    console.error('[Supabase] Failed to initialize client:', error);
    throw error;
  }
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _initError: Error | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    try {
      if (!_supabase && !_initError) {
        _supabase = createSupabaseClient();
      }
      if (_initError) {
        throw _initError;
      }
      return Reflect.get(_supabase!, prop, receiver);
    } catch (error) {
      _initError = error as Error;
      console.error('[Supabase] Client access failed:', error);
      throw error;
    }
  },
});

