// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

let _supabase: ReturnType<typeof createClient<Database>> | null = null;

export function getSupabaseClient() {
  if (_supabase) {
    return _supabase;
  }

  try {
    const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      console.error('[Supabase] Missing environment variables');
      console.error('[Supabase] VITE_SUPABASE_URL:', SUPABASE_URL ? '✓' : '✗');
      console.error('[Supabase] VITE_SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✓' : '✗');
      return null;
    }

    _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    });

    console.log('[Supabase] Client initialized');
    return _supabase;
  } catch (error) {
    console.error('[Supabase] Initialization error:', error);
    return null;
  }
}

// Create a proxy that safely returns null instead of throwing
export const supabase = new Proxy({}, {
  get(target, prop) {
    const client = getSupabaseClient();
    if (!client) {
      console.warn(`[Supabase] Client not available, cannot access: ${String(prop)}`);
      return undefined;
    }
    return Reflect.get(client, prop);
  }
}) as unknown as ReturnType<typeof createClient<Database>>;

